// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ExtrapagesDocumentDataSlicesSlice = never;

/**
 * Content for extrapages documents
 */
interface ExtrapagesDocumentData {
  /**
   * Slice Zone field in *extrapages*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: extrapages.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExtrapagesDocumentDataSlicesSlice> /**
   * Meta Description field in *extrapages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: extrapages.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *extrapages*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: extrapages.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *extrapages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: extrapages.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * extrapages document from Prismic
 *
 * - **API ID**: `extrapages`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExtrapagesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExtrapagesDocumentData>,
    "extrapages",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | SafetyTipsSectionSlice
  | EnquiresSectionSlice
  | AccessoriesDisplaySectionSlice
  | CustomerSatisfactionSectionSlice
  | ProductsOfTheWeekSlice
  | HeroSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *custom-settings → navigations*
 */
export interface NavDocumentDataNavigationsItem {
  /**
   * link field in *custom-settings → navigations*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navigations[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * label field in *custom-settings → navigations*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navigations[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;
}

type NavDocumentDataSlicesSlice =
  | AccessoriesSlice
  | UsedLaptopsSlice
  | ProductsSlice;

/**
 * Content for custom-settings documents
 */
interface NavDocumentData {
  /**
   * logo field in *custom-settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Site Title field in *custom-settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * meta description field in *custom-settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * og image field in *custom-settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Address field in *custom-settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  address: prismic.KeyTextField;

  /**
   * RefundPolicy field in *custom-settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.refundpolicy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  refundpolicy: prismic.LinkField;

  /**
   * DeliveryPolicy field in *custom-settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.deliverypolicy
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  deliverypolicy: prismic.LinkField;

  /**
   * TermsAndConditions field in *custom-settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.termsandconditions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  termsandconditions: prismic.LinkField;

  /**
   * PhoneNumber field in *custom-settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.phonenumber
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phonenumber: prismic.KeyTextField;

  /**
   * Email field in *custom-settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * navigations field in *custom-settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.navigations[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigations: prismic.GroupField<Simplify<NavDocumentDataNavigationsItem>>;

  /**
   * Slice Zone field in *custom-settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: nav.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NavDocumentDataSlicesSlice>;
}

/**
 * custom-settings document from Prismic
 *
 * - **API ID**: `nav`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<NavDocumentData>, "nav", Lang>;

type ProductsDocumentDataSlicesSlice = never;

/**
 * Content for products documents
 */
interface ProductsDocumentData {
  /**
   * Slice Zone field in *products*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: products.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductsDocumentDataSlicesSlice> /**
   * Meta Description field in *products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: products.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: products.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * products document from Prismic
 *
 * - **API ID**: `products`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductsDocumentData>,
    "products",
    Lang
  >;

export type AllDocumentTypes =
  | ExtrapagesDocument
  | HomeDocument
  | NavDocument
  | ProductsDocument;

/**
 * Primary content in *Accessories → Default → Primary*
 */
export interface AccessoriesSliceDefaultPrimary {
  /**
   * AccessoryBrandName field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.accessorybrandname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accessorybrandname: prismic.KeyTextField;

  /**
   * AccessoryTitle field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.accessorytitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  accessorytitle: prismic.KeyTextField;

  /**
   * ShortDescription field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.shortdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shortdescription: prismic.KeyTextField;

  /**
   * FullDescription field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.fulldescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fulldescription: prismic.KeyTextField;

  /**
   * AccessoryPrice field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.accessoryprice
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  accessoryprice: prismic.NumberField;

  /**
   * MainAccessoryImage field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.mainaccessoryimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainaccessoryimage: prismic.ImageField<never>;

  /**
   * ComplimentaryAccessoryImage1 field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.complimentaryaccessoryimage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryaccessoryimage1: prismic.ImageField<never>;

  /**
   * ComplimentaryAccessoryImage2 field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.complimentaryaccessoryimage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryaccessoryimage2: prismic.ImageField<never>;

  /**
   * ComplimentaryAccessoryImage3 field in *Accessories → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories.default.primary.complimentaryaccessoryimage3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryaccessoryimage3: prismic.ImageField<never>;
}

/**
 * Default variation for Accessories Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccessoriesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AccessoriesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Accessories*
 */
type AccessoriesSliceVariation = AccessoriesSliceDefault;

/**
 * Accessories Shared Slice
 *
 * - **API ID**: `accessories`
 * - **Description**: Accessories
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccessoriesSlice = prismic.SharedSlice<
  "accessories",
  AccessoriesSliceVariation
>;

/**
 * Primary content in *AccessoriesDisplaySection → Default → Primary*
 */
export interface AccessoriesDisplaySectionSliceDefaultPrimary {
  /**
   * Question field in *AccessoriesDisplaySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories_display_section.default.primary.question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Writeup field in *AccessoriesDisplaySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: accessories_display_section.default.primary.writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup: prismic.KeyTextField;
}

/**
 * Default variation for AccessoriesDisplaySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccessoriesDisplaySectionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<AccessoriesDisplaySectionSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *AccessoriesDisplaySection*
 */
type AccessoriesDisplaySectionSliceVariation =
  AccessoriesDisplaySectionSliceDefault;

/**
 * AccessoriesDisplaySection Shared Slice
 *
 * - **API ID**: `accessories_display_section`
 * - **Description**: AccessoriesDisplaySection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccessoriesDisplaySectionSlice = prismic.SharedSlice<
  "accessories_display_section",
  AccessoriesDisplaySectionSliceVariation
>;

/**
 * Primary content in *CustomerSatisfactionSection → Default → Primary*
 */
export interface CustomerSatisfactionSectionSliceDefaultPrimary {
  /**
   * Header field in *CustomerSatisfactionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_satisfaction_section.default.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Writeup field in *CustomerSatisfactionSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: customer_satisfaction_section.default.primary.writeup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  writeup: prismic.KeyTextField;
}

/**
 * Default variation for CustomerSatisfactionSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerSatisfactionSectionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<CustomerSatisfactionSectionSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *CustomerSatisfactionSection*
 */
type CustomerSatisfactionSectionSliceVariation =
  CustomerSatisfactionSectionSliceDefault;

/**
 * CustomerSatisfactionSection Shared Slice
 *
 * - **API ID**: `customer_satisfaction_section`
 * - **Description**: CustomerSatisfactionSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CustomerSatisfactionSectionSlice = prismic.SharedSlice<
  "customer_satisfaction_section",
  CustomerSatisfactionSectionSliceVariation
>;

/**
 * Primary content in *EnquiresSection → Default → Primary*
 */
export interface EnquiresSectionSliceDefaultPrimary {
  /**
   * PhoneNumber field in *EnquiresSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: enquires_section.default.primary.phonenumber
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phonenumber: prismic.KeyTextField;
}

/**
 * Default variation for EnquiresSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnquiresSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EnquiresSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EnquiresSection*
 */
type EnquiresSectionSliceVariation = EnquiresSectionSliceDefault;

/**
 * EnquiresSection Shared Slice
 *
 * - **API ID**: `enquires_section`
 * - **Description**: EnquiresSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EnquiresSectionSlice = prismic.SharedSlice<
  "enquires_section",
  EnquiresSectionSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * HeroWriteUp field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.herowriteup
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herowriteup: prismic.KeyTextField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *NewLaptops → Default → Primary*
 */
export interface ProductsSliceDefaultPrimary {
  /**
   * LaptopBrandName field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.laptopbrandname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  laptopbrandname: prismic.KeyTextField;

  /**
   * LaptopTitle field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.laptoptitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  laptoptitle: prismic.KeyTextField;

  /**
   * ShortDescription field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.shortdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shortdescription: prismic.KeyTextField;

  /**
   * FullDescription field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.fulldescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fulldescription: prismic.KeyTextField;

  /**
   * LaptopPrice field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.laptopprice
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  laptopprice: prismic.NumberField;

  /**
   * MainLaptopImage field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.mainlaptopimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainlaptopimage: prismic.ImageField<never>;

  /**
   * ComplementaryImage1 field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.complementaryimage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complementaryimage1: prismic.ImageField<never>;

  /**
   * ComplementaryImage2 field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.complementaryimage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complementaryimage2: prismic.ImageField<never>;

  /**
   * ComplementaryImage3 field in *NewLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.complementaryimage3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complementaryimage3: prismic.ImageField<never>;
}

/**
 * Default variation for NewLaptops Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewLaptops*
 */
type ProductsSliceVariation = ProductsSliceDefault;

/**
 * NewLaptops Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<
  "products",
  ProductsSliceVariation
>;

/**
 * Item in *ProductsOfTheWeek → Default → Primary → Products*
 */
export interface ProductsOfTheWeekSliceDefaultPrimaryProductsItem {
  /**
   * ProductBrandName field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].productbrandname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  productbrandname: prismic.KeyTextField;

  /**
   * ProductTitle field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].producttitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  producttitle: prismic.KeyTextField;

  /**
   * ShortDescription field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].shortdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shortdescription: prismic.KeyTextField;

  /**
   * FullDescription field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].fulldescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fulldescription: prismic.KeyTextField;

  /**
   * ProductPrize field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].productprize
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  productprize: prismic.NumberField;

  /**
   * MainProductImage field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].mainproductimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainproductimage: prismic.ImageField<never>;

  /**
   * ComplimentoryProductImage1 field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].complimentoryproductimage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentoryproductimage1: prismic.ImageField<never>;

  /**
   * ComplimentoryProductImage2 field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].complimentoryproductimage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentoryproductimage2: prismic.ImageField<never>;

  /**
   * ComplimentoryProductImage3 field in *ProductsOfTheWeek → Default → Primary → Products*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[].complimentoryproductimage3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentoryproductimage3: prismic.ImageField<never>;
}

/**
 * Primary content in *ProductsOfTheWeek → Default → Primary*
 */
export interface ProductsOfTheWeekSliceDefaultPrimary {
  /**
   * HeaderTitle field in *ProductsOfTheWeek → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.headertitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  headertitle: prismic.KeyTextField;

  /**
   * Products field in *ProductsOfTheWeek → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products_of_the_week.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<ProductsOfTheWeekSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for ProductsOfTheWeek Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsOfTheWeekSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsOfTheWeekSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProductsOfTheWeek*
 */
type ProductsOfTheWeekSliceVariation = ProductsOfTheWeekSliceDefault;

/**
 * ProductsOfTheWeek Shared Slice
 *
 * - **API ID**: `products_of_the_week`
 * - **Description**: ProductsOfTheWeek
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsOfTheWeekSlice = prismic.SharedSlice<
  "products_of_the_week",
  ProductsOfTheWeekSliceVariation
>;

/**
 * Item in *SafetyTipsSection → Default → Primary → SafetyTip*
 */
export interface SafetyTipsSectionSliceDefaultPrimarySafetytipItem {
  /**
   * Tip field in *SafetyTipsSection → Default → Primary → SafetyTip*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: safety_tips_section.default.primary.safetytip[].tip
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tip: prismic.KeyTextField;
}

/**
 * Primary content in *SafetyTipsSection → Default → Primary*
 */
export interface SafetyTipsSectionSliceDefaultPrimary {
  /**
   * SafetyTip field in *SafetyTipsSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: safety_tips_section.default.primary.safetytip[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  safetytip: prismic.GroupField<
    Simplify<SafetyTipsSectionSliceDefaultPrimarySafetytipItem>
  >;
}

/**
 * Default variation for SafetyTipsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SafetyTipsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SafetyTipsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SafetyTipsSection*
 */
type SafetyTipsSectionSliceVariation = SafetyTipsSectionSliceDefault;

/**
 * SafetyTipsSection Shared Slice
 *
 * - **API ID**: `safety_tips_section`
 * - **Description**: SafetyTipsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SafetyTipsSectionSlice = prismic.SharedSlice<
  "safety_tips_section",
  SafetyTipsSectionSliceVariation
>;

/**
 * Primary content in *UsedLaptops → Default → Primary*
 */
export interface UsedLaptopsSliceDefaultPrimary {
  /**
   * LaptopBrandName field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.laptopbrandname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  laptopbrandname: prismic.KeyTextField;

  /**
   * LaptopTitle field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.laptoptitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  laptoptitle: prismic.KeyTextField;

  /**
   * ShortDescription field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.shortdescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  shortdescription: prismic.KeyTextField;

  /**
   * FullDescription field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.fulldescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  fulldescription: prismic.KeyTextField;

  /**
   * LaptopPrice field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.laptopprice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  laptopprice: prismic.KeyTextField;

  /**
   * MainLaptopImage field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.mainlaptopimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainlaptopimage: prismic.ImageField<never>;

  /**
   * ComplimentaryImage1 field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.complimentaryimage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryimage1: prismic.ImageField<never>;

  /**
   * ComplimentaryImage2 field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.complimentaryimage2
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryimage2: prismic.ImageField<never>;

  /**
   * ComplimentaryImage3 field in *UsedLaptops → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: used_laptops.default.primary.complimentaryimage3
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  complimentaryimage3: prismic.ImageField<never>;
}

/**
 * Default variation for UsedLaptops Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UsedLaptopsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UsedLaptopsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *UsedLaptops*
 */
type UsedLaptopsSliceVariation = UsedLaptopsSliceDefault;

/**
 * UsedLaptops Shared Slice
 *
 * - **API ID**: `used_laptops`
 * - **Description**: UsedLaptops
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UsedLaptopsSlice = prismic.SharedSlice<
  "used_laptops",
  UsedLaptopsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ExtrapagesDocument,
      ExtrapagesDocumentData,
      ExtrapagesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      NavDocument,
      NavDocumentData,
      NavDocumentDataNavigationsItem,
      NavDocumentDataSlicesSlice,
      ProductsDocument,
      ProductsDocumentData,
      ProductsDocumentDataSlicesSlice,
      AllDocumentTypes,
      AccessoriesSlice,
      AccessoriesSliceDefaultPrimary,
      AccessoriesSliceVariation,
      AccessoriesSliceDefault,
      AccessoriesDisplaySectionSlice,
      AccessoriesDisplaySectionSliceDefaultPrimary,
      AccessoriesDisplaySectionSliceVariation,
      AccessoriesDisplaySectionSliceDefault,
      CustomerSatisfactionSectionSlice,
      CustomerSatisfactionSectionSliceDefaultPrimary,
      CustomerSatisfactionSectionSliceVariation,
      CustomerSatisfactionSectionSliceDefault,
      EnquiresSectionSlice,
      EnquiresSectionSliceDefaultPrimary,
      EnquiresSectionSliceVariation,
      EnquiresSectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      ProductsSlice,
      ProductsSliceDefaultPrimary,
      ProductsSliceVariation,
      ProductsSliceDefault,
      ProductsOfTheWeekSlice,
      ProductsOfTheWeekSliceDefaultPrimaryProductsItem,
      ProductsOfTheWeekSliceDefaultPrimary,
      ProductsOfTheWeekSliceVariation,
      ProductsOfTheWeekSliceDefault,
      SafetyTipsSectionSlice,
      SafetyTipsSectionSliceDefaultPrimarySafetytipItem,
      SafetyTipsSectionSliceDefaultPrimary,
      SafetyTipsSectionSliceVariation,
      SafetyTipsSectionSliceDefault,
      UsedLaptopsSlice,
      UsedLaptopsSliceDefaultPrimary,
      UsedLaptopsSliceVariation,
      UsedLaptopsSliceDefault,
    };
  }
}
