// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  accessories_display_section: dynamic(
    () => import("./AccessoriesDisplaySection"),
  ),
  customer_satisfaction_section: dynamic(
    () => import("./CustomerSatisfactionSection"),
  ),
  enquires_section: dynamic(() => import("./EnquiresSection")),
  hero_section: dynamic(() => import("./HeroSection")),
  products_of_the_week: dynamic(() => import("./ProductsOfTheWeek")),
  safety_tips_section: dynamic(() => import("./SafetyTipsSection")),
};
